# frontend/fly.toml

app = "deb-qcd4za" # Your actual frontend app name
primary_region = "iad" # Or your chosen region

[build]
dockerfile = "Dockerfile"
[build.args]
# Correctly set for production build
REACT_APP_API_URL = "https://deb.fly.dev"

[http_service]
internal_port = 8080 # Port Caddy listens on inside container
force_https = true
auto_stop_machines = true # Or 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

# [[vm]] # Optional VM settings can go here if needed
#   cpu_kind = "shared"
#   cpus = 1
#   memory_mb = 256 # Example for a small frontend

# [[http_service.checks]] # Optional health checks can go here