# fly.toml file generated for your-bible-frontend-app-name on 2023-10-27T10:05:00-07:00

app = "your-bible-frontend-app-name" # Replace with your actual frontend app name
primary_region = "iad" # Use the same region as the backend, or choose others

[build]
  # Reference the Dockerfile in the current directory
  dockerfile = "Dockerfile"
  # Pass the API URL during the Docker build process
  [build.args]
    REACT_APP_API_URL = "https://your-bible-backend-app-name.fly.dev" # Placeholder, will be set by Action

[http_service]
  internal_port = 8080 # Port Caddy listens on inside the container
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# Optional: Add health checks if Caddy provides one or serve a static file
# [[http_service.checks]]
#   interval = "10s"
#   timeout = "2s"
#   grace_period = "5s"
#   method = "GET"
#   path = "/" # Check if the root path returns 200 OK