# frontend/fly.toml

app = "your-frontend-app-name" # Your actual frontend app name
primary_region = "iad" # Or your chosen region

[build]
dockerfile = "Dockerfile"
[build.args]
# !!! SET THIS TO YOUR ACTUAL BACKEND URL !!!
REACT_APP_API_URL = "https://deb.fly.dev" # <---- Make sure this is correct

[http_service]
internal_port = 8080 # Port Caddy listens on
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

# ... (Optional checks) ...